#+INCLUDE: "../../../common/header-examen-practica.org"

#+OPTIONS: author:nil date:nil 

#+LATEX_HEADER: \lhead{IAW}
#+LATEX_HEADER: \rhead{Instancia de Wordpress}

#+title: Instalación de Wordpress

* Objetivos de la práctica:
En esta práctica se espera que el alumno:
- Utilice un proveedor externo para su pila LAMP
- Instale Wordpress de forma manual
- Conozca los niveles de acceso de Wordpress

* Enunciado
Una empresa de servicios informáticos desea crear una página web para la autopromoción y  comunicación con sus clientes.

Los contenidos de la página web serán los siguientes:
- Una presentación de la empresa: qué servicios ofrece, tipos de proyectos (instalación de redes, mantenimiento de ordenadores, instalación de servidores, creación de páginas web)...
- Formas de contacto: perfiles en redes sociales, correo electrónico, teléfono, localización geográfica,...
- Noticias de interés sobre la empresa, para que sean leídas por clientes futuros y actuales
  
En dicha empresa hay un departamento de informática (usuario =Administrador=), que será el encargado de manejar dicha página web. El jefe de ventas (usuario =Enrique=) será el responsable de los contenidos de las páginas, pero no los escribirá él directamente, sino que ese trabajo lo llevarán a cabo dos de sus empleados: =Alicia= y =Roberto=. Las noticias las escribirán también otros empleados (=Juan= y =Susana=), pero tendrán que ser revisadas por el jefe de ventas antes de ser publicadas.

* /Hosting/
Se debe elegir un /hosting/ externo para el desarrollo de la práctica. Se sugiere:
- https://www.awardspace.com/free-web-hosting-registration/   (no funciona con un email de educamadrid)
- https://profreehost.com/ (bastante lento)
- Es válido cualquier otro /hosting/ de terceros con
  - Acceso a ficheros FTP, SSH (o interfaz web)
  - Servidor MySQL
  - Ejecución de PHP    

* Requisitos
Se pide que configures un servidor web con Wordpress capaz de servir este sitio, con los requisitos anteriores.
- Cada tarea deberá realizarla el usuario adecuado para ello (el de menor nivel de acceso)
- Configurar el servidor, los usuarios, la apariencia general, el logotipo de la empresa,...
- Será necesario también cambiar el tema de wordpress, instalando uno nuevo (por ejemplo, desde [[https://wordpress.org/themes/browse/community/]])

El sitio tendrá:
- Una página de inicio con imágenes y un menú al resto de páginas
- Una página de /Quiénes somos/
- Una página con las últimas noticias
- Habrá al menos tres noticias. Todas tendrán un fichero PDF que podrá descargarse.       

* Normas de entrega
Se pide la URL de un sitio web con Wordpress instalado, cumpliendo las normas anteriores. Se incluirá también un usuario y contraseña con nivel /Administrador/.

La entrega se realizará en la tarea correspondiente del [[https://aulavirtual3.educa.madrid.org/ies.alonsodeavellan.alcala/][aula virtual]].

La autoría del trabajo será individual.
