#+TITLE: Practica de análisis de riesgos

#+INCLUDE: "../../../common/header-examen-practica.org"

#+OPTIONS: author:nil date:nil 

#+LATEX_HEADER: \lhead{Análisis de riesgos}
#+LATEX_HEADER: \rhead{Seguridad y alta disponibilidad}


* ENUNCIADO

La empresa Europe Avellaneda S.A. se dedica a la organización de eventos. Por ejemplo, organiza fiestas de presentación de productos, desfiles de moda, joyería, grandes actos públicos, como festivales musicales, representaciones teatrales en fiestas de grandes ciudades, etc.

En su sede central, situada en una céntrica calle de Madrid, disponen de unas instalaciones con varios despachos. En la oficina trabajan varios representantes, cuya función principal es estar en contacto con proveedores y clientes, para terminar de organizar el evento.

Cada representante puede conectarse a la red wifi de la empresa con su portátil. En esa red, que es privada, existe una aplicación desarrollada dentro de la empresa (llamada Testor) en la que se almacenan los datos de clientes, eventos y proveedores.

A dicha aplicación se accede con un navegador (es decir, es una Aplicación web), pero el servidor es privado. Para acceder a dicha aplicación, es necesario estar conectado a la wifi de la oficina (no se accede desde Internet) y además introducir un nombre de usuario y una contraseña.

Un representante tiene acceso a los datos de sus eventos y de sus clientes, a los datos de todos los proveedores, y a la información de eventos ya realizados y los clientes que los encargaron, así como a los datos del representante que gestionó el evento.

Para mayor comodidad de los representantes la red Wi-fi permite también el acceso a Internet. Y supuestamente, desde Internet no se puede acceder a la aplicación de Testor.

Un día, un comercial estaba trabajando con su portátil. Había iniciado sesión en Testor, y estaba revisando algunos de los datos a los que estaba autorizado a ver. De repente, se encendió la luz de la webcam. También observó que aparecía en la barra de Windows, durante un par de segundos el nombre de un programa que desconocía.

Pasó el tiempo y el incidente fue tomado simplemente como una anécdota. Pero, al cabo de un par de semanas, un cliente llamó a nuestro representante y le informó de que cancelaba un evento importante, cuyos detalles eran supuestamente secretos porque se había puesto en contacto con él otro representante de otra empresa ofreciéndole la realización del evento a menor coste.

Este nuevo representante conocía detalles que sólo en Europe Avellaneda S.A. debían saber.

El proyecto cancelado iba a ser facturado por unos 720.000€. Después de pagar a proveedores y después de impuestos, el beneficio neto para la empresa sería de unos 65.000€, de los cuales, el 10% supondría una jugosa comisión para el representante.

El cliente no cedió el proyecto a la otra empresa de eventos, sino que lo canceló por completo: si poca confianza le inspiraba Europe Avellaneda, menos confianza le inspiraba otra empresa que intentaba llevarse el contrato del evento.

El incidente alarmó a la gerencia de la empresa, que nos encarga que estudiemos el caso, para que no vuelva a ocurrir que alguien de la competencia intenta llevarse un evento. Y no solo eso, sino evitar la falta de credibilidad que va a tener durante un tiempo esta empresa.

* Parte 1: Análisis de riesgos
- Realiza un análisis de riesgos de este caso.
- Recuerda que es un análisis de riesgos:
  - Identificamos elementos relacionados con el ataque (o con el supuesto ataque en caso de no poder confirmarse).
  - Amenazas, riesgos, activos implicados, vulnerabilidades de cada activo.
  - Describimos el impacto del ataque (si se hubiera producido) o de las posibles amenazas en caso de que se materializasen.
  - Describimos las actividades de negocio afectadas y en qué medida.
  - Describimos el objetivo de quien nos encarga el análisis (¿qué queremos lograr?).
  - Enumeramos las medidas de seguridad que existen y evaluamos su eficacia.
  - Proponemos soluciones (medidas de seguridad), de manera ordenada, con descripción de las bondades de esta, sus costes (iniciales y de mantenimiento).
- Sugerimos el conjunto de medidas de seguridad que pensamos más adecuado de entre las aportadas.
- Un análisis de riesgos es un documento técnico, con el estudio de un caso por parte de un profesional: tú, dirigido a una o varias personas implicadas en la gerencia de una empresa u organización.
- Aún no estamos en condiciones de proponer las cosas con mucho detalle técnico, pero nadie va a cuestionar tus aportes en materia de medidas de seguridad. Tan solo, que el análisis sea correcto en sus formas.

* Parte 2: Políticas de seguridad
¿Hay alguna norma de seguridad que quieras que los empleados de Europe Avellaneda cumplan? Si es así, detállala en el cuadro de notas que hay al final de este ejercicio.
- Con una o dos líneas por cada cosa que sugieras es suficiente.
- Si no es necesario tener en cuenta ninguna consideración adicional que deba ser conocida por el personal de Europe Avellaneda, indícalo también, mencionando que no es necesario incluir ninguna política de seguridad nueva.
- Recuerda que son normas dirigidas a personal no técnico: lenguaje sencillo y claro.
- La gerencia de la empresa lo leerá y si aprueba nuestras sugerencias, se incluirán en el documento de Políticas de Seguridad de la empresa.


* Plantilla
Puedes usar esta [[file:sad-01-plantilla-analisis-riesgos.docx][plantilla para la elaboración de la práctica]].

