#+INCLUDE: "../../../common/header-examen-practica.org"

#+OPTIONS: author:nil date:nil 

#+LATEX_HEADER: \lhead{IAW}
#+LATEX_HEADER: \rhead{Práctica PHP (III)}

#+title: Tercera práctica PHP

#+latex: \attachfile{../UT04//tiles/tiles.zip}  

* Objetivos de la práctica:
:PROPERTIES:
:UNNUMBERED: t
:END:
En esta práctica se espera que el alumno:
- Se familiarice con el uso de MySQL
- Utilice técnicas AJAX para mejorar la usabilidad de sus aplicaciones web
- Proteja la aplicación de ataques /SQL injection/ y /HTML injection/ 


Se tomará como base el código desarrollado para la práctica anterior

* /CRUD/ de mazmorras (3 puntos)
Modifica =listado-mazmorras.php=
- El botón de crear una nueva mazmorra solo podrá pulsarse si el campo de texto no está vacío, y el nombre de mazmorra aún no existe.
  - hay que tener en cuenta que otros usuarios pueden estar creando mazmorras
  - Debe ser una petición AJAX, no puede descargarse una lista de nombres prohibidos al comienzo de la página (40%)
- El borrado de mazmorra no recargará la página (60%)
  - La fila de la tabla aparecerá tachada, y los botones deshabilitados
  - Si se recarga la página, entonces sí que ya no aparecerá la fila  
    
* Duplicar mazmorra (1 punto)
Modifica =duplicar-mazmorra.php=. Está página
- El botón de duplicar mazmorra solo se podrá pulsar si el nuevo nombre no está vacío, y el nombre de mazmorra aún no existe.

* Ataques con el nombre de la mazmorra (-3 puntos)
Si se puede [[https://kunststube.net/escapism/][atacar la aplicación con nombres de mazmorra maliciosos]], se restarán 3 puntos del total de la práctica

#+latex: \begin{Aviso}[Cómo me defiendo]
- [[https://www.php.net/manual/en/function.htmlspecialchars.php][=htmlspecialchars=]]
- [[https://www.w3schools.com/php/php_mysql_prepared_statements.asp][Sentencias preparadas]]  
#+latex: \end{Aviso}
  
* Editar mazmorra  (5 puntos)
Modifica =editar-mazmorra.php=. Esta página:
- Inicialmente, estará seleccionada la imagen =E.png= en la paleta
- Si se hace click sobre otro item de la paleta, se seleccionará  
- Bastará con hacer click en la mazmorra para sustituir esa tesela por la seleccionada en la paleta.

* Recomendaciones
:PROPERTIES:
:UNNUMBERED: t
:END:
- Crea una o varias páginas (por ejemplo =api-mazmorras.php=) donde se dirigirán las peticiones AJAX
- Si usas JSON  
  - Estas páginas no generarán HTML, sino JSON como respuesta
  - Tampoco recibirán parámetros de formulario, sino que leerán la entrada, que será un JSON
- Como alternativa, se puede usar un formato propio
  - Se envían formularios POST con valores
  - Se generan páginas de texto, o XML, que se comprueban en el javascript cliente  
      

  


* Normas de entrega
:PROPERTIES:
:UNNUMBERED: t
:END:
- El código estará en el directorio =~/public-html/practica03/= del /workspace/ de Coder del alumno
  - El profesor copiará las páginas a su propio LAMP para corregir la práctica
  - El profesor se encargará de cambiar los datos de acceso a MySQL.
  - Las páginas deberán crear las tablas que necesiten, si no no se podrá corregir la práctica.
- Los nombres de fichero PHP y los nombres de funciones serán los especificados en los enunciados
- Todos los formularios serán *GET*
  - Si no se pueden ver los parámetros en la URL, el ejercicio no tendrá más del 50% de la nota  
- Se recuerda que los alumnos deben guardar una copia de seguridad de todos sus trabajos, en el caso de que Coder no funcione
- *No deben aparcer errores ni avisos de PHP*. Hay que tener en cuenta que se ejecutarán con opciones de /debug/, como =display_errors= a =true=
  - Puede ser útil: =isset()=, =is_numeric()=, =floatval()=
  - Si hay errores o avisos, el ejercicio no tendrá más del 50% de la nota
- No se tendrán en cuenta:
  - Errores debidos al reenvío de formularios por duplicado (por recarga de página)
  - Errores debidos a parámetros cambiados a mano para teselas/mazmorras que no existen
  - Errores debidos a excesiva latencia de la respuesta del servidor  
      
* Resultados de aprendizaje
:PROPERTIES:
:UNNUMBERED: t
:END:
Esta práctica contribuye a la calificación de los siguientes RA:
- RA 5: parte de "prácticas"
- RA 6: parte de "prácticas"

* URLS a probar :noexport:


https://443s--main--p3--admin.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--adrianalvarez10.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--eduardoanton1.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--agarcia190.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--alejandrojimenez34.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--ismaelmacareno.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--ivanmarin1.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--pablonunez16.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--aroaperez2.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--pabloramo.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--jorgeramos6.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--miguelreyes1.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--joserojas12.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--oskarsajek.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--alvarosanchez308.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--andreasantosesteban.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--fernandovaquerizo.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--alvarovicente1.coder.iesavellaneda.es/public-html/practica02
https://443s--main--iaw--veronicavillaseca.coder.iesavellaneda.es/public-html/practica02



