#+INCLUDE: "../../../common/header.org"
#+TITLE:  Unified Modeling Language (UML)
#+REVEAL_HLEVEL: 1

* UML
- Lenguaje Unificado de Modelado
- Conjunto de diagramas para modelar y documentar un sistema software
  - Misma idea que los diagramas E-R de base de datos.
- Es un estándar de facto
- Su origen es la fusión de varios métodos orientación a objetos:
  - OMT - Object Modeling Technique (Jim Rumbaugh et al.).
  - Método-Booch (Grady Booch).
  - OOSE - Object-Oriented Software Engineering (Ivar Jacobson) .

** Por qué modelar
- Mejor documentación
  - Un diagrama es más rápido de entender que un texto largo
  - Un diagrama suele ser menos ambiguo que un texto
  - Permite la comunicación efectiva entre miembros del equipo
- Desarrollo rápido
  - Más rápido que la implementación en código
  - Algunas herramientas permiten generar código a partir de los diagramas    

** Cuándo modelar    
- Ingeniería directa
  - Se diseña el sistema usando (entre otros) diagramas UML
  - Después se implementa
- Ingeniería inversa
  - Se estudia un sistema ya existente
  - Se crean diagramas UML para mejorar la comprensión

** Tipos de diagramas
- Diagramas de clases
- Diagramas de casos de uso
- Diagramas de

** Herramientas
- Lápiz y papel
- [[https://editor.plantuml.com/uml][Plantuml]] y [[https://www.umlet.com/][UMLet]]
- Prácticamente cualquier herramienta de diagramas      

* Diagramas de clases

#+MACRO: src-to-dataurl (eval (let* ((name $1) (info (org-babel-get-src-block-info 'light)) (body (with-current-buffer (current-buffer) (org-babel-goto-named-src-block name) (nth 1 (org-babel-get-src-block-info 'light)))))   (concat "data:text/plain;base64," (base64-encode-string (string-as-unibyte body) t))))
          
- Rectángulo: una clase
  - Cada línea es un método o atributo
  - ~#~ para protegido, ~+~ para público, ~-~ para privado
- Línea: relación entre clases (una referencia)
  - Cardinalidad: como en E-R
  - Con triángulo: herencia
  - Con rombo hueco: agregación (tiene varias instancias)
  - Con rombo lleno: composición (se compone de varias instancias, similar a una entidad débil E-R)  

** Ejemplo con PlantUML    

#+name: leyenda-clases    
#+begin_src plantuml :file media/leyenda-clases.svg
@startuml

' === Clases e interfaces ===
interface Vehiculo {
  +mover()
}

class Coche {
  +matricula: String
  -atributoPrivado: Int
  #metodoProtegido()
  +mover()
}

class Motor
class Rueda
class Persona

' === Herencia (generalización) ===
Vehiculo <|-- Coche

' === Composición (parte fuerte, ciclo de vida dependiente) ===
Coche *-- Motor : composición

' === Agregación (parte débil) ===
Coche *-- Rueda : composición

Coche o-- Viajes : Agregación


' === Relación con cardinalidad ===
Persona "1" -- "0..*" Coche : posee


@enduml
#+end_src

** Ejemplo:

- Un curso está compuesto por varias asignaturas.
- Cada alumno pertenece a un único curso, aunque un curso puede tener muchos alumnos.
- Un profesor puede impartir varias asignaturas, y una asignatura puede ser impartida por un único profesor.
- Las asignaturas se dividen en dos tipos: teóricas y prácticas, utilizando herencia.
- Un alumno se matricula en asignaturas mediante una matrícula.
- La matrícula representa la relación entre un alumno y el conjunto de asignaturas en las que está inscrito.
- Las calificaciones de un alumno en cada asignatura se almacenan en una clase llamada Nota.
- Cada matrícula debe permitir:
  - Registrar una calificación para una asignatura (setNota(asignatura, valor)).
  - Consultar la calificación de una asignatura (getNota(asignatura)).

#+reveal: split  

#+begin_src plantuml :file media/profesores-y-asignaturas.svg
@startuml

class Profesor {
}

class Alumno {
}

class Curso {
}

class Asignatura {
}

class AsignaturaPractica {
}

class AsignaturaTeorica {
}

class Matricula {
    +setNota(asignatura, valor)
    +getNota(asignatura)
}


' Herencia
Asignatura <|-- AsignaturaPractica
Asignatura <|-- AsignaturaTeorica

' Relaciones curso-asignaturas
Curso "1" *-- "1..*" Asignatura : compone

' Alumno pertenece a un curso
Curso "0..*" <-- "0..*" Alumno : pertenece

' Profesor imparte asignaturas
Profesor "1" -- "0..*" Asignatura : imparte

' Matricula
Alumno "1" -- "1..*" Matricula
Matricula "1" *-- "1..*" Asignatura : incluye

@enduml
#+end_src

#+RESULTS:
[[file:media/profesores-y-asignaturas.svg]]

** Ejercicio
- Una empresa quiere manejar el stock de un almacén
- Cada venta indica qué productos incluye, y la cantidad de cada uno, y a qué precio
- Cada entrada en el almacén indica qué productos incluye, y la cantidad de cada uno
- El gestor del almacén se encarga de que no haya ventas que sobrepasen el /stock/ de ningún producto
- Se puede preguntar a una venta por su importe       

#+begin_src plantuml :file media/stock-almacen.svg
  @startuml

class Producto {
  - nombre : String
  - stock : int
  + getStock() : int
  + aumentarStock(cantidad : int)
  + disminuirStock(cantidad : int)
}

class Venta {
  - fecha : Date
  - lineas : List<LineaVenta>
  + getImporte() : double
}

class LineaVenta {
  - cantidad : int
  - precio : double
  + getSubtotal() : double
}

class Entrada {
  - fecha : Date
  - lineas : List<LineaEntrada>
}

class LineaEntrada {
  - cantidad : int
}

class Almacen {
  - cantidad : int
  + getStock(Producto): int
  + validaVenta(Venta): Boolean      
}

Almacen "1" o-- "0..*" Producto
Almacen "1" o-- "0..*" Venta
Almacen "1" o-- "0..*" Entrada



Producto "1" -- "0..*" LineaVenta
Producto "1" -- "0..*" LineaEntrada

Venta "1" *-- "1..*" LineaVenta
Entrada "1" *-- "1..*" LineaEntrada



@enduml
#+end_src

#+RESULTS:
[[file:media/stock-almacen.svg]]


* Vigencia de UML
- UML es comparable a los diagramas E-R
- No se usa mucho de forma "oficial" en las empresas
- Pero es muy útil para aclaraciones en reuniones y documentación de requisitos complicados
      
* Referencias
#+include: "../../../common/footer.org"



