   
#+INCLUDE: "../../../common/header-examen-practica.org"

#+OPTIONS: author:nil date:nil toc:nil title:nil

#+LATEX_HEADER: \lhead{Trabajo de scripts de shell}
#+LATEX_HEADER: \rhead{ASGBD}
#+LATEX_HEADER: \usepackage{tabularx}


La última versión de este documento se puede descargar de [[https://alvarogonzalezsotillo.github.io/apuntes-clase/sistemas-gestores-bbdd-asir2/apuntes/3/asgbd-03-trabajo-scripts-2026.pdf]]




* /Scripts/ de inicio y parada de *Oracle* (1 punto)

Crea dos /scripts/ para iniciar y parar *Oracle*. Deben controlar el /listener/, la instancia y las /pluggable database/
  - =/home/alumno/scripts/oraclestart.sh=
  - =/home/alumno/scripts/oraclestop.sh=
 



* Crea usuarios de base de datos (2 puntos)
  - Crea un script de nombre =/home/alumno/scripts/nuevos-usuarios-oracle.sh= que lea de su entrada estándar
  - Cada línea será un nombre de usuario a crear
  - Cada usuario se creará con permisos connect y resource
    - La contraseña será aleatoria. Se indicará la contraseña de cada usuario creado
  - Si el usuario ya existe, no se hará nada con él, y se indicará claramente
 
  #+caption: Ejemplo de uso
  #+name: lst:nuevos-usuarios-ejemplo
  #+begin_src bash
  echo "pepe\njuan\nmanolo" | ./nuevos-usuarios-oracle.sh
  pepe: no existe, se crea con contraseña 12384738 y se le dan roles
  juan: ya existe, no se hace nada
  manolo: no existe, se crea con contraseña 8272729 y se le dan roles
  #+end_src

#+latex: \begin{Aviso}
Puedes usar =read -r= en un =while= para leer las filas de la entrada estándar.
#+latex: \end{Aviso}

  
* Borra un usuario de la base de datos (2 puntos)      
  - Crea un script de nombre =/home/alumno/scripts/quita-usuario-oracle.sh= que bloquee el usuario pasado como parámetro
    - Si el usuario no existe, informará de ello y tendrá un errorlevel de =1=
    - Si se invoca con primer parámetro =--drop= y segundo el usuario, borrará el usuario.
    - Si se invoca sin parámetros, o incorrectos, mostrará el texto de ayuda del listado [[lst:quita-usuario-ayuda]]  

  #+caption: Ayuda del script =quita-usuario-oracle.sh=
  #+name: lst:quita-usuario-ayuda
  #+begin_src bash

  Borra o bloquea un usuario de oracle.
  
  Uso: quita-usuario-oracle.sh <usuario>
       quita-usuario-oracle.sh --drop <usuario>
  #+end_src
   
#+latex: \begin{Aviso}
  En la salida del /script/ debe quedar claro si el usuario se borra o bloquea
#+latex: \end{Aviso} 
 

* Envía un correo periódicamente (2 puntos)
  - Programa un /script/ para que cada minuto envíe un correo con un resumen del uso de disco por cada /tablespace/ permanente:
    - Nombre de /tablespace/, fichero del /tablespace/, tamaño en /bytes/.
  - El destino será =alvaro@alvarogonzalez.no-ip.biz=, con copia a tu usuario local
    - Con la copia podéis saber si el correo se ha enviado
  - Indica tu nombre en el asunto del correo  
  - El fichero tendrá [[https://stackoverflow.com/questions/643137/how-do-i-spool-to-a-csv-formatted-file-using-sqlplus#654723][formato CSV]]. Se debe poder abrir directamente con *excel* y visualizar su resultado en filas y columnas.


* Instrucciones de entrega

- El ejercicio se realizará y entregará de manera individual. Solo se puede hacer por parejas si no hay ordenadores suficientes.
- Sube en la tarea del aula virtual un ZIP con todos los ficheros que has creado o modificado:
  - /Scripts/
  - /units/ de =systemd=
  - Ficheros de =cron= / =anacron=
- Deben llegar varios correos a =alvaro@alvarogonzalez.no-ip.biz=    
  
